// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hilylerjxusicrqizbwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpbHlsZXJqeHVzaWNycWl6Ynd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODE2NzAsImV4cCI6MjA2NjM1NzY3MH0.CEdIjtleCVCbosZIGrK3_Juw4HfMORe2DXVhDDm-GAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);